{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-superheat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/superheat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/superheat/superheat_{{ version }}.tar.gz
  sha256: 03bdc76167e10e0fbfcf3ef849399fa3a018b29ec35f53a954aeccd0afd16807

build:
  noarch: generic
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr >=0.4.3
    - r-ggdendro
    - r-ggplot2 >=2.0.0
    - r-gtable >=0.1.2
    - r-magrittr >=1.5
    - r-plyr >=1.8.3
    - r-scales >=0.3.0
  run:
    - r-base
    - r-dplyr >=0.4.3
    - r-ggdendro
    - r-ggplot2 >=2.0.0
    - r-gtable >=0.1.2
    - r-magrittr >=1.5
    - r-plyr >=1.8.3
    - r-scales >=0.3.0

test:
  commands:
    - $R -e "library('superheat')"  # [not win]
    - "\"%R%\" -e \"library('superheat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=superheat
  license: CC0-1.0
  summary: A system for generating extendable and customizable heatmaps for exploring complex datasets, including big data and data with multiple data types.
  license_family: CC
  license_file:
    - LICENSE-CC0

extra:
  recipe-maintainers:
    - conda-forge/r
